### ISSUE TITLE
No Rotated BBoxes

### ISSUE THREAD

**Issue by arasharchor** [cgvict/roLabelImg#3]
### Rotation Bounsing box does not work.
I am trying to annotate a ship using the rotated BBox feature, but it is exactly the same as BBox feature without rotation. I am using PyQt4 and not 5.
![screenshot from 2017-08-29 11-11-51](https://user-images.githubusercontent.com/12903362/29813949-e6b66630-8cab-11e7-8bc2-7bd478ea2d64.png)

- **OS:** Ubuntu16.04

- **PyQt version:** below
```
from PyQt4.QtCore import QT_VERSION_STR
from PyQt4.pyqtconfig import Configuration
print("Qt version:", QT_VERSION_STR)
('Qt version:', '4.8.7')
cfg = Configuration()
 print("PyQt version:", cfg.pyqt_version_str)
('PyQt version:', '4.11.4')
```

**Comment by ycg1024** [comment]
Try to use Hotkeys described in README ?

**Comment by koro33e** [comment]
@smajida Try to use Hotkeys described in README ?

**Comment by arasharchor** [comment]
@ycg1024 thanks it works. I missed that last Hotkey. IHowever, the angle rotation seems to be wrong. Could you please take a look at it and confirm it? I annotated two ships with zero and 90 degrees. both annotations are 0 degrees. Then I annotated another ship with 45 degrees, but the angle is around 2.88. What does this number mean and what is its scale?

t is possible to set a default degree of bounding box and remains until we change it directly. then it again remains the same until be changed directly. In this way it would save a lot of time.

**Comment by lihui52** [comment]
@smajida I met the same problem. How did you solve it?

**Comment by arasharchor** [comment]
@lihui52 you have to open rotation labelme file and not not-rotation labelme python file. by pressing a button which honeslty I do not remember you can turn bounding box.

**Comment by sarathsrk** [comment]
That keys are 
z & x for Anti-Clockwise rotation
c & v for Clockwise rotation

**Comment by arasharchor** [comment]
It is working properly.
