### ISSUE TITLE
Save output as YOLO txt format

### ISSUE THREAD

**Issue by danzigjabalpur** [cgvict/roLabelImg#8]
Hi, can someone help point me to which part of the code do I modify in order to save output as yolo format in txt file please

<label/class ID> <x-center> <y-center> <width> <height>
e.g  0 0.643333 0.166667 0.252222 0.318519

**Comment by GuanRainy** [comment]
read ‘xml’ information and use follow function code to convert it to yolo format 
`def convert(size, box):
    dw = 1./size[0]
    dh = 1./size[1]
    x = (box[0] + box[1])/2.0
    y = (box[2] + box[3])/2.0
    w = box[2] - box[0]
    h = box[3] - box[1]
    x = x*dw
    w = w*dw
    y = y*dh
    h = h*dh
    return (x,y,w,h)`

**Comment by RuaYahya** [comment]
Can you share with us if you been able to save it to yolo format...
Thanks in advance.

**Comment by ManasaNadimpalli** [comment]
Can we save the rotated rectangle boxes coordinates in yolo format?
Thanks in advance.

**Comment by danzigjabalpur** [comment]
It is possible to convert the boxes into yolo format but you would also need the rotation information otherwise the boxes would be wrong. other than that, you'd have to modify yolo to accept the rotation info when training and predicting... that being said, ill be closing this issue
